### ISSUE TITLE
[Not issue, compilation fix] Cannot compile with libplist>=2.3.0, however the latest libimobiledevice-glue needs 2.3.0

### ISSUE THREAD

**Issue by waterdragon78** [libimobiledevice/idevicerestore#624]
Hello! I just want to share an issue I had compiling this and how I fixed it for the people who get the error:

``ipsw.c:135:9: error: too few arguments to function ‘plist_from_memory’``

Basically, when using the libplist 2.3.0 (latest 2.4.0 also tried) and the latest libimobiledevice-glue, this error generated for me. When I remove libplist 2.3.0 and install libplist-dev from apt, and use this commit of libimobiledevice-glue (`https://github.com/libimobiledevice/libimobiledevice-glue/tree/90fc3833203192ff5a6009d339454b0265b4efc1`, which only requires 2.2.0 which is libplist-dev from apt), it compiled. I just wanted to raise awareness for this bug.

**Comment by nikias** [comment]
You are not using the latest code for idevicerestore, then it would work. Since commit 7321192b1bd3781ca214f575d63e2df4b0fdade2 from almost a year ago, idevicerestore is using libplist-2.3.0 which contains the breaking change.
